modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="leonmtr"
version="1.0.9"
displayName="Leon轨道交通Mod"
displayURL="https://modrinth.com/mod/leonmtrmod"
credits="感谢永盛服主林枫酱和云山服主Spentwing！"
authors="LeonMMcoset"
description="已开源，可更改。"

[[dependencies.leonmtr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




