modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="leonmtr"
version="1.1.3"
displayName="Leon\u8F68\u9053\u4EA4\u901AMod"
displayURL="https://modrinth.com/mod/leonmtrmod"
credits="\u611F\u8C22\u6C38\u76DB\u670D\u4E3B\u6797\u67AB\u9171\u548C\u4E91\u5C71\u670D\u4E3BSpentwing\uFF01"
authors="LeonMMcoset"
description="\u5DF2\u5F00\u6E90\uFF0C\u53EF\u66F4\u6539\u3002"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.leonmtr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration